#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: $[mysql.account.url]
      username: $[mysql.account.username]
      password: $[mysql.account.password]
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initial-size: 5   #初始化连接个数
      min-idle: 5       #最小连接个数
      max-active: 20    #最大连接个数
      max-wait: 60000   #配置获取连接等待超时的时间
      pool-prepared-statements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20  #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      time-between-eviction-runs-millis: 60000   # 配置检测间隔时间，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 100000     # 配置一个连接在池中最小生存的时间
      validation-query: SELECT 1 FROM DUAL    #用来检测连接是否有效的sql
      validation-query-timeout: 6000  #检查sql超时时间
      test-while-idle: true    #申请连接的时候检测
      test-on-borrow: false   #申请连接时执行validationQuery检测连接是否有效
      test-on-return: false   #归还连接时执行validationQuery检测连接是否有效
      use-global-data-source-stat: true  #合并多个DruidDataSource的监控数据
      filters: stat,wall          #配置扩展插件
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      aop-patterns: com.syx.nian.*..servie.*  # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      # 配置监控服务器
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*   # 访问路径为/druid时，跳转到StatViewServlet
        reset-enable: false # 是否能够重置数据
        login-username: admin
        login-password: 123456
      #      allow: 127.0.0.1  # IP白名单
      #      deny: 192.168.1.218  #IP黑名单（共同存在时，deny优先于allow）
      web-stat-filter:
        url-pattern: /*    # 添加过滤规则
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"     # 忽略过滤格式
      filter:  # 配置StatFilter
        stat:
          log-slow-sql: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml        #映射文件所在路径，可以多个，中间以都好隔开
  type-aliases-package: com.syx.nian.demo.ali.core.entity    #pojo类所在包路径
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true



pagehelper:
  supportMethodsArguments: true
  offsetAsPageNum: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql  # <!-- 和startPage中的pageNum效果一样-->
  rowBoundsWithCount: true  #<!-- 设置为true时，使用RowBounds分页会进行count查询 -->

